"""agrego promociones

Revision ID: 0d74b0aa7ab5
Revises: 1bed33e3778b
Create Date: 2026-07-30 00:27:51.147222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d74b0aa7ab5'
down_revision: Union[str, None] = '1bed33e3778b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promociones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio_promocional', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocion_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promocion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['promocion_id'], ['promociones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ventas', sa.Column('descuento_promociones', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'descuento_promociones')
    op.drop_table('promocion_items')
    op.drop_table('promociones')
    # ### end Alembic commands ###
