"""agrego configuracion de recargos

Revision ID: 1f6a6fbc22b1
Revises: 7a4998dc0cdb
Create Date: 2026-07-23 11:14:05.068808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6a6fbc22b1'
down_revision: Union[str, None] = '7a4998dc0cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recargo_cigarrillos', sa.Numeric(precision=6, scale=4, asdecimal=False), nullable=True),
    sa.Column('recargo_credito', sa.Numeric(precision=6, scale=4, asdecimal=False), nullable=True),
    sa.Column('recargo_debito', sa.Numeric(precision=6, scale=4, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion')
    # ### end Alembic commands ###
