"""agrego anulacion de ventas

Revision ID: 642691d130ad
Revises: d5839b1539b1
Create Date: 2026-07-19 20:24:40.608528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642691d130ad'
down_revision: Union[str, None] = 'd5839b1539b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('anulada', sa.Boolean(), nullable=True))
    op.add_column('ventas', sa.Column('fecha_anulacion', sa.DateTime(), nullable=True))
    op.add_column('ventas', sa.Column('motivo_anulacion', sa.String(length=200), nullable=True))
    op.add_column('ventas', sa.Column('anulada_por_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ventas', 'usuarios', ['anulada_por_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventas', type_='foreignkey')
    op.drop_column('ventas', 'anulada_por_id')
    op.drop_column('ventas', 'motivo_anulacion')
    op.drop_column('ventas', 'fecha_anulacion')
    op.drop_column('ventas', 'anulada')
    # ### end Alembic commands ###
