"""agrego ventas suspendidas

Revision ID: 7a4998dc0cdb
Revises: 642691d130ad
Create Date: 2026-07-23 00:53:09.238259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4998dc0cdb'
down_revision: Union[str, None] = '642691d130ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###   

    inspector = sa.inspect(op.get_bind())

    if inspector.has_table("ventas_suspendidas"):
        return

    op.create_table('ventas_suspendidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.String(length=100), nullable=True),
    sa.Column('datos_json', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas_suspendidas')
    # ### end Alembic commands ###
