"""recupero tabla ventas_suspendidas

Revision ID: a703da909e7e
Revises: 212c6ee167a7
Create Date: 2026-07-25 15:26:50.144113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a703da909e7e'
down_revision: Union[str, None] = '212c6ee167a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion')
    op.alter_column('productos', 'pendiente_revision',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint('productos_ibfk_3', 'productos', type_='foreignkey')
    op.drop_column('productos', 'creado_por_id')
    op.drop_column('productos', 'aprobado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('aprobado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('creado_por_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('productos_ibfk_3', 'productos', 'usuarios', ['creado_por_id'], ['id'])
    op.alter_column('productos', 'pendiente_revision',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_table('configuracion',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recargo_cigarrillos', mysql.DECIMAL(precision=6, scale=4), nullable=True),
    sa.Column('recargo_credito', mysql.DECIMAL(precision=6, scale=4), nullable=True),
    sa.Column('recargo_debito', mysql.DECIMAL(precision=6, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
