"""agrego aprobacion de productos

Revision ID: c23921f924bc
Revises: 1f6a6fbc22b1
Create Date: 2026-07-23 21:38:07.434392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23921f924bc'
down_revision: Union[str, None] = '1f6a6fbc22b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('aprobado', sa.Boolean(), nullable=True))
    op.add_column('productos', sa.Column('creado_por_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'productos', 'usuarios', ['creado_por_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_column('productos', 'creado_por_id')
    op.drop_column('productos', 'aprobado')
    # ### end Alembic commands ###
