"""agrego debito a ventas

Revision ID: d5839b1539b1
Revises: 963953286409
Create Date: 2026-07-18 16:47:04.167749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5839b1539b1'
down_revision: Union[str, None] = '963953286409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('debito', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'debito')
    # ### end Alembic commands ###
